version: '3.7'
services:
  midway_search:
    build:
      context: ./midway_search/
    ports:
      - "7866:7866"
      - "8090:8090"
    volumes:
      - /storage/kliffeup/kliffeup/allknower/data/:/app/data/
      - /storage/kliffeup/kliffeup/allknower/common/:/app/common/
  blender:
    build:
      context: blender_scoring_service
    ports:
      - "8767:8767"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['5']
              capabilities: [gpu]
