name: branch name check

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  branch-name-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Validate branch name
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

          # Define the pattern: feature/AK[sprint_number]-[ticket-number-within-sprint]{/developer-nickname-in-GitHub]} -- last part in curly brackets is optional and can be omitted
          PATTERN="^feature\/AK[1-9]\d*-[1-9]\d*(\/[a-zA-Z0-9-]+)?$"

          if [[ ! $BRANCH_NAME =~ $PATTERN ]]; then
            echo "Error: branch name '$BRANCH_NAME' does not match the naming convention."
            echo "Please use the PATTERN: feature/AK[sprint_number]-[ticket-number-within-sprint]{/developer-nickname-in-GitHub]} -- last part in curly brackets is optional and can be omitted"
            exit 1
          fi
